name: Build

on:
  push:
    branches:
      - master
  #   paths:
  #     - projects/lib/package.json
  #     - projects/lib/package-lock.json
  #     - .github/workflows/build.yaml
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: publish
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build:ci
      - uses: pascalgn/npm-publish-action@1.3.8
        with:
          package: "./projects/lib/package.json"
          token: ${{ secrets.NPM_TOKEN }}
        run: echo "Version change, <${{ steps.publish.outputs.type }}> ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
      # - run: npm publish --access public
      #   working-directory: projects/lib
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
