name: Build

on:
  push:
    branches:
      - master
  #   paths:
  #     - projects/lib/package.json
  #     - projects/lib/package-lock.json
  #     - .github/workflows/build.yaml
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build:ci
      - uses: pascalgn/npm-publish-action@1.3.8
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
          workspace: "projects/lib"
          publish_command: "yarn"
          publish_args: "--non-interactive"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - run: npm publish --access public
      #   working-directory: projects/lib
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
